//! VNCCad desktop autosave store: one `<key>.dxf` plus `<key>.json` per drawing in the user's
//! data folder (Windows: %LOCALAPPDATA%\VNCCad\autosave; macOS: ~/Library/Application
//! Support/VNCCad/autosave; Linux: $XDG_DATA_HOME or ~/.local/share/VNCCad/autosave).
//! `VNCCAD_AUTOSAVE_DIR` overrides the folder.

use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use cadcraft_ui_egui::autosave::{AutosaveEntry, AutosaveStore, age_text};
use serde_json::{Value, json};

fn now_ms() -> f64 {
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs_f64() * 1000.0).unwrap_or(0.0)
}

fn dir() -> Option<PathBuf> {
    if let Some(d) = std::env::var_os("VNCCAD_AUTOSAVE_DIR") {
        return Some(PathBuf::from(d));
    }
    let base = if cfg!(windows) {
        std::env::var_os("LOCALAPPDATA").or_else(|| std::env::var_os("APPDATA")).map(PathBuf::from)
    } else if cfg!(target_os = "macos") {
        std::env::var_os("HOME").map(|h| PathBuf::from(h).join("Library").join("Application Support"))
    } else {
        std::env::var_os("XDG_DATA_HOME")
            .map(PathBuf::from)
            .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".local").join("share")))
    };
    base.map(|b| b.join("VNCCad").join("autosave"))
}

/// Keys are generated by us (`<run>-<uid>`); refuse anything else so a key can never name a
/// file outside the folder.
fn safe(key: &str) -> bool {
    !key.is_empty() && key.len() < 80 && key.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
}

fn write_atomic(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let tmp = path.with_extension("tmp");
    std::fs::write(&tmp, bytes).map_err(|e| e.to_string())?;
    std::fs::rename(&tmp, path).map_err(|e| e.to_string())
}

/// VNCCad: where a preference (`key` made of letters, digits, `-`, `_`) is kept: next to the
/// autosave folder.
pub fn pref_path(key: &str) -> Option<PathBuf> {
    if key.is_empty() || !key.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_') {
        return None;
    }
    Some(dir()?.parent()?.join("prefs").join(format!("{key}.json")))
}

pub fn store() -> Option<AutosaveStore> {
    let dir = dir()?;
    let run_tag = format!("{}p{}", now_ms() as u64, std::process::id());
    let (d1, d2, d3, d4) = (dir.clone(), dir.clone(), dir.clone(), dir.clone());
    Some(AutosaveStore {
        run_tag,
        interval_s: 120.0,
        location: dir.to_string_lossy().to_string(),
        put: Box::new(move |key, title, path, dxf| {
            if !safe(key) {
                return Err("invalid key".into());
            }
            std::fs::create_dir_all(&d1).map_err(|e| format!("{}: {e}", d1.display()))?;
            write_atomic(&d1.join(format!("{key}.dxf")), dxf)?;
            let meta = json!({ "title": title, "path": path, "time": now_ms() });
            write_atomic(&d1.join(format!("{key}.json")), meta.to_string().as_bytes())
        }),
        list: Box::new(move || {
            let Ok(rd) = std::fs::read_dir(&d2) else { return Vec::new() };
            let now = now_ms();
            let mut out: Vec<(f64, AutosaveEntry)> = rd
                .flatten()
                .filter_map(|e| {
                    let p = e.path();
                    if p.extension().and_then(|x| x.to_str()) != Some("json") {
                        return None;
                    }
                    let key = p.file_stem()?.to_str()?.to_string();
                    if !safe(&key) || !d2.join(format!("{key}.dxf")).is_file() {
                        return None;
                    }
                    let meta: Value = serde_json::from_slice(&std::fs::read(&p).ok()?).ok()?;
                    let time = meta.get("time").and_then(Value::as_f64).unwrap_or(0.0);
                    let title = meta.get("title").and_then(Value::as_str).unwrap_or("Bản vẽ").to_string();
                    let path = meta.get("path").and_then(Value::as_str).map(str::to_string);
                    Some((time, AutosaveEntry { key, title, path, age: age_text(now - time) }))
                })
                .collect();
            out.sort_by(|a, b| b.0.total_cmp(&a.0));
            out.into_iter().map(|(_, e)| e).collect()
        }),
        get: Box::new(move |key| if safe(key) { std::fs::read(d3.join(format!("{key}.dxf"))).ok() } else { None }),
        remove: Box::new(move |key| {
            if safe(key) {
                let _ = std::fs::remove_file(d4.join(format!("{key}.dxf")));
                let _ = std::fs::remove_file(d4.join(format!("{key}.json")));
            }
        }),
    })
}
